# Generated by Django 5.2.1 on 2025-06-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='created_by',
        ),
    ]
